<a href="https://colab.research.google.com/github/IamSaransh/Pytorch/blob/main/PytprchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(pd.__version__)
print(np.__version__)

2.4.0+cu121
2.1.4
1.26.4


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introdution to tensors
### creating tensor

In [4]:
# scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [5]:
scalar.ndim

0

In [6]:
#get tensor back as python int
scalar.item()

10

In [7]:
#vector
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matirx
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
# Matirx
MATRIX2 = torch.tensor([[7,8],
                       [9,10], [11,10]])

In [12]:
MATRIX2.ndim

2

In [13]:
MATRIX.shape, MATRIX2.shape

(torch.Size([2, 2]), torch.Size([3, 2]))

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape
# you have 1 3x3 tensor

torch.Size([1, 3, 3])

 ### Random tensorts

In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9080, 0.7479, 0.9572, 0.4419],
        [0.9234, 0.4698, 0.7920, 0.9449],
        [0.3018, 0.6096, 0.8061, 0.1572]])

In [19]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,  random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones tensor

In [20]:
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones((3,4), dtype=torch.int32)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [22]:
ones.dtype

torch.int32

In [23]:
range = torch.arange(0,1000, step = 88)
range

tensor([  0,  88, 176, 264, 352, 440, 528, 616, 704, 792, 880, 968])

In [24]:
zeros_in_same_shape = torch.zeros_like(input=range)
zeros_in_same_shape

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,1,1])
torch.matmul(tensor1, tensor2.T)

<ipython-input-25-ed2a3174fb75>:3: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3697.)
  torch.matmul(tensor1, tensor2.T)


tensor(6)

In [26]:
tensor1 = torch.rand(3,4)
tensor2 = torch.rand(3,4)
torch.matmul(tensor1.mT, tensor2)

tensor([[0.1969, 0.6864, 0.7984, 0.7608],
        [0.2175, 0.2436, 0.8337, 0.6341],
        [0.1054, 0.2824, 0.3204, 0.3681],
        [0.1386, 0.4694, 0.9081, 0.5474]])

In [31]:
linear = torch.nn.Linear(in_features=4, out_features=12)
input = tensor1
output = linear(input)
output

tensor([[ 0.1936, -0.0060,  0.2578,  0.0021,  0.2261, -0.2496,  0.0993,  0.8517,
         -0.3750,  0.0957,  0.3704,  0.0039],
        [-0.0710,  0.0808,  0.0755, -0.0896,  0.3762, -0.3235,  0.3479,  0.7445,
         -0.0706,  0.0637,  0.1282, -0.2796],
        [ 0.1543,  0.4494,  0.3188, -0.4210,  0.1583, -0.2674,  0.0609,  0.6747,
         -0.1821,  0.0589,  0.1349, -0.2185]], grad_fn=<AddmmBackward0>)

In [32]:
input.shape, output.shape

(torch.Size([3, 4]), torch.Size([3, 12]))

In [31]:
x = torch.arange(0,100,step = 10, dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [32]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0.0
Maximum: 90.0
Mean: 45.0
Sum: 450.0


In [ ]:
#squeeze and unsqueeze tensors
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[0, 9]' is invalid for input of size 9

In [ ]:
z = x.view(3,3)
z[:,0] = 100
z, x

(tensor([[100.,   2.,   3.],
         [100.,   5.,   6.],
         [100.,   8.,   9.]]),
 tensor([100.,   2.,   3., 100.,   5.,   6., 100.,   8.,   9.]))